server:
  servlet:
    port: 8080
    contextPath: /api

spring:
  application:
    name:

  datasource:
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/quora
#      username:postgres
#      password:postgres
    url: jdbc:postgresql://ec2-54-145-224-156.compute-1.amazonaws.com:5432/d3lvj5hjkm3irv
    username:fbnxduajrwusyr
    password:c7c53a1ba5ecb4fa40736433eb7493c73c8f3d10465dec084fd920f3d16bf5bd

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect