server:
  servlet:
    port: 8080
    contextPath: /api

spring:
  application:
    name:

  datasource:
    driverClassName: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/quora
    #      username:postgres
    #      password:postgres
    url: jdbc:postgresql://ec2-54-225-228-142.compute-1.amazonaws.com:5432/d9nmh4nu5hb0bo
    username: dxhbgcsdlqtxnu
    password: 7000e9b44ef15dee6135b5fa6dc04e127105b2687178ece1b90759524a10ec71

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect